asia:
  - IN: "India"
  - ID: "Indonesia"
  - KR: "Korea"
  - KH: "Cambodia"
  - GU: "Guam"
  - MP: "Saipan"
  - SG: "Singapore"
  - LK: "Sri Lanka"
  - TH: "Thailand"
  - TW: "Taiwan"
  - CN: "China"
  - NP: "Nepal"
  - PK: "Pakistan"
  - BD: "Bangladesh"
  - PH: "Philippines"
  - BT: "Bhutan"
  - BN: "Brunei"
  - VN: "Vietnam"
  - HK: "Hong Kong"
  - MO: "Macao"
  - MY: "Malaysia"
  - MM: "Myanmar"
  - MV: "Maldives"
  - MN: "Mongolia"
  - LA: "Laos"
oceania:
  - AU: "Australia"
  - SB: "Solomon"
  - NC: "New Caledonia"
  - NZ: "New Zealand"
  - PG: "Papua New Guinea"
  - FJ: "Fiji"
nc_america:
  - US: "United States"
  - SV: "El Salvador"
  - CA: "Canada"
  - CU: "Cuba"
  - CR: "Costa Rica"
  - JM: "Jamaica"
  - TT: "Trinidad and Tobago"
  - PA: "Panama"
  - BB: "Barbados"
  - HN: "Honduras"
  - MX: "Mexico"
middle_east:
  - AE: "United Arab Emirates"
  - IL: "Israel"
  - IQ: "Iraq"
  - IR: "Iran"
  - OM: "Oman"
  - QA: "Qatar"
  - CY: "Cyprus"
  - KW: "Kuwait"
  - SA: "Saudi Arabia"
  - SY: "Syria"
  - TR: "Turkey"
  - BH: "Bahrain"
  - JO: "Jordan"
europe:
  - IS: "Iceland"
  - IE: "Ireland"
  - AZ: "Azerbaijan"
  - IT: "Italy"
  - UA: "Ukraine"
  - GB: "United Kingdom"
  - EE: "Estonia"
  - AT: "Austria"
  - NL: "Netherlands"
  - GR: "Greece"
  - HR: "Croatia"
  - CH: "Switzerland"
  - SE: "Sweden"
  - ES: "Spain"
  - SK: "Slovakia"
  - SI: "Slovenia"
  - CZ: "Czech Republic"
  - DK: "Denmark"
  - DE: "Germany"
  - NO: "Norway"
  - HU: "Hungary"
  - FI: "Finland"
  - FR: "France"
  - BG: "Bulgaria"
  - BY: "Belarus"
  - BE: "Belgium"
  - PL: "Poland"
  - PT: "Portugal"
  - MK: "Macedonia"
  - MT: "Malta"
  - MC: "Monaco"
  - LV: "Latvia"
  - LT: "Lithuania"
  - LI: "Liechtenstein"
  - LU: "Luxembourg"
  - RO: "Romania"
  - RU: "Russian Federation"
south_america:
  - AR: "Argentina"
  - UY: "Uruguay"
  - EC: "Ecuador"
  - CO: "Colombia"
  - CL: "Chile"
  - PY: "Paraguay"
  - BR: "Brazil"
  - VE: "Venezuela"
  - PE: "Peru"
africa:
  - DZ: "Algeria"
  - UG: "Uganda"
  - EG: "Egypt"
  - ET: "Ethiopia"
  - GH: "Ghana"
  - GA: "Gabon"
  - KE: "Kenya"
  - CI: "Cote d'Ivoire"
  - SL: "Sierra Leone"
  - DJ: "Djibouti"
  - ZW: "Zimbabwe"
  - SD: "Sudan"
  - SN: "Senegal"
  - TZ: "Tanzania"
  - TN: "Tunisia"
  - TG: "Togo"
  - NG: "Nigeria"
  - BW: "Botswana"
  - MG: "Madagascar"
  - ZA: "Republic of South Africa"
  - MU: "Mauritius"
  - MA: "Morocco"
  - RW: "Rwanda"